import dotenv from "dotenv";
dotenv.config();

import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Crucial middleware for body-parsing
  app.use(express.json());

  // API to generate a high quality 3-round debate using Gemini
  app.post("/api/debate", async (req, res) => {
    try {
      const { topic } = req.body;
      if (!topic || typeof topic !== "string" || !topic.trim()) {
        res.status(400).json({ error: "Topic is required" });
        return;
      }

      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey) {
        res.status(500).json({
          error: "GEMINI_API_KEY environment variable is not configured. Please define it in the AI Studio Settings > Secrets panel."
        });
        return;
      }

      // Initialize the official Google GenAI SDK as guided by the gemini-api skill
      const ai = new GoogleGenAI({
        apiKey: apiKey,
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build"
          }
        }
      });

      const prompt = `You are a savage debate show host generating a hilarious 3-round debate 
to help someone decide: "${topic.trim()}"

PERSONA RULES — these MUST sound completely different:
KAI = Positive Focus Metaphors. Borderline delusional with absolute assurance in his experiences. Uses overly optimistic analogies, spiritual/experiential alignment, and visualizes success with absolute certainty. Speaks with boundless enthusiasm, using metaphors of growth, flow, quantum shifts, and life-changing personal journeys.
NATALIE = Assertive, Calm Demeanor, and Observative. Focuses strictly on facts, scientific validation, and analytical data over feelings. Calmly but assertively dissects KAI's claims using logic, statistics, and objective realities. Never raises her voice or loses composure, but remains absolute in her factual correctness.

STRUCTURE: 3 rounds. KAI opens, NATALIE responds. Exactly 2 punchy sentences each.

RULES:
- Use SPECIFIC, FUNNY, REAL details about "${topic.trim()}" — no generic filler
- KAI must express absolute alignment and positive delusional assurance
- NATALIE must respond with concrete, factual observations and a calm, assertive tone
- Do NOT decide a winner. Set winner to null. The audience votes.
- Do NOT write In conclusion or anything formal`;

      // Call the model using correct generateContent patterns as per SDK specification 
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              topic: { type: Type.STRING },
              sideA: { type: Type.STRING, description: "KAI's side (3 words max)" },
              sideB: { type: Type.STRING, description: "NATALIE's side (3 words max)" },
              rounds: {
                type: Type.ARRAY,
                items: {
                  type: Type.OBJECT,
                  properties: {
                    speaker: { type: Type.STRING, description: "Must be 'KAI' or 'NATALIE'" },
                    argument: { type: Type.STRING }
                  },
                  required: ["speaker", "argument"]
                }
              },
              winner: { type: Type.NULL }
            },
            required: ["topic", "sideA", "sideB", "rounds"]
          }
        }
      });

      const text = response.text;
      if (!text) {
        throw new Error("No output generated by the Gemini model");
      }

      const parsedDebate = JSON.parse(text.trim());
      res.json(parsedDebate);
    } catch (error: any) {
      console.error("Synthesizing debate failed:", error);
      res.status(500).json({ error: error.message || "Synthesizing debate failed" });
    }
  });

  // Vite middleware for development vs static asset delivery for production
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
  });
}

startServer();
